-- ==========================================
-- COMPLETE SETUP FOR NOTE SHARING APP
-- Includes: Notes Table, Storage Buckets, and Notice Board
-- ==========================================

-- 1. Create Notes Table
-- 1. Create Notes Table (if not exists)
create table if not exists notes (
  id bigint primary key generated by default as identity,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  subject text not null,
  semester integer not null,
  written_by text not null,
  file_url text not null,
  exam_type text default 'Class Note',
  is_pinned boolean default false
);

-- Ensure exam_type column exists (for existing tables)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'notes' and column_name = 'exam_type') then
    alter table notes add column exam_type text default 'Class Note';
  end if;
end $$;

-- 2. Enable Row Level Security (RLS)
alter table notes enable row level security;

-- 3. Create Policies (Drop first to avoid errors)
drop policy if exists "Enable read access for all users" on notes;
create policy "Enable read access for all users"
  on notes for select
  using ( true );

drop policy if exists "Enable insert for authenticated users only" on notes;
create policy "Enable insert for authenticated users only"
  on notes for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Enable delete for authenticated users only" on notes;
create policy "Enable delete for authenticated users only"
  on notes for delete
  using ( auth.role() = 'authenticated' );

drop policy if exists "Enable update for authenticated users only" on notes;
create policy "Enable update for authenticated users only"
  on notes for update
  using ( auth.role() = 'authenticated' );

-- 4. Create Storage Bucket for PDFs
insert into storage.buckets (id, name, public)
values ('notes', 'notes', true)
on conflict (id) do nothing;

-- 5. Storage Policies (Drop first)
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'notes' );

drop policy if exists "Auth Upload Access" on storage.objects;
create policy "Auth Upload Access"
  on storage.objects for insert
  with check ( bucket_id = 'notes' and auth.role() = 'authenticated' );

drop policy if exists "Auth Delete Access" on storage.objects;
create policy "Auth Delete Access"
  on storage.objects for delete
  using ( bucket_id = 'notes' and auth.role() = 'authenticated' );

-- 6. Refresh Schema
notify pgrst, 'reload schema';

-- ==========================================
-- NOTICE BOARD SETUP
-- ==========================================

-- 7. Create Notices Table
create table if not exists notices (
  id bigint primary key generated by default as identity,
  content text not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Enable RLS for Notices
alter table notices enable row level security;

-- 9. Notices Policies (Drop first)
drop policy if exists "Public notices are viewable by everyone" on notices;
create policy "Public notices are viewable by everyone"
  on notices for select
  using ( true );

drop policy if exists "Admins can insert notices" on notices;
create policy "Admins can insert notices"
  on notices for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Admins can update notices" on notices;
create policy "Admins can update notices"
  on notices for update
  using ( auth.role() = 'authenticated' );

-- 10. Default Content
insert into notices (id, content, is_active)
values (1, 'Welcome to NoteShare! Exam updates will appear here.', true)
on conflict (id) do nothing;