-- ==========================================
-- COMPLETE SUPABASE SETUP & UPDATE SCRIPT
-- ==========================================
-- Run this entire script in the Supabase SQL Editor.
-- It will handle both NEW setups and EXISTING setups safely.

-- 1. Create 'notes' table (If it doesn't exist)
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  subject text not null,
  semester int not null,
  file_url text not null,
  -- We include 'title' for backwards compatibility but it's nullable now
  title text 
);

-- 2. Add 'written_by' column (If missing)
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name = 'notes' and column_name = 'written_by') then
    alter table public.notes add column written_by text;
  end if;
end $$;

-- 3. Make 'title' nullable (If it was NOT NULL before)
alter table public.notes alter column title drop not null;

-- 4. Enable RLS (Security)
alter table public.notes enable row level security;

-- 5. Create Policies (Use DO block to avoid "policy already exists" errors)
do $$ 
begin
  if not exists (select 1 from pg_policies where policyname = 'Public notes are viewable by everyone') then
    create policy "Public notes are viewable by everyone" on public.notes for select to public using (true);
  end if;
  
  if not exists (select 1 from pg_policies where policyname = 'Admins can insert notes') then
    create policy "Admins can insert notes" on public.notes for insert to authenticated with check (true);
  end if;

  if not exists (select 1 from pg_policies where policyname = 'Admins can update notes') then
    create policy "Admins can update notes" on public.notes for update to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where policyname = 'Admins can delete notes') then
    create policy "Admins can delete notes" on public.notes for delete to authenticated using (true);
  end if;
end $$;

-- 6. Storage Setup (Bucket 'notes')
insert into storage.buckets (id, name, public) 
values ('notes', 'notes', true)
on conflict (id) do nothing;

-- 7. Storage Policies
do $$ 
begin
  if not exists (select 1 from pg_policies where tablename = 'objects' and policyname = 'Give public access to files') then
    create policy "Give public access to files" on storage.objects for select to public using ( bucket_id = 'notes' );
  end if;
  
  if not exists (select 1 from pg_policies where tablename = 'objects' and policyname = 'Give admin access to upload') then
    create policy "Give admin access to upload" on storage.objects for insert to authenticated with check ( bucket_id = 'notes' );
  end if;
end $$;

-- 8. Refresh Schema Cache (Crucial for seeing new columns immediately)
notify pgrst, 'reload schema';
