-- ==========================================
-- COMPLETE SETUP FOR NOTE SHARING APP
-- Includes: Notes Table, Storage Buckets, and Notice Board
-- ==========================================

-- 1. Create Notes Table
create table if not exists notes (
  id bigint primary key generated by default as identity,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  subject text not null,
  semester integer not null,
  written_by text not null,
  file_url text not null
);

-- 2. Enable Row Level Security (RLS)
alter table notes enable row level security;

-- 3. Create Policies (Public Read, Admin Write)
create policy "Enable read access for all users"
  on notes for select
  using ( true );

create policy "Enable insert for authenticated users only"
  on notes for insert
  with check ( auth.role() = 'authenticated' );

create policy "Enable delete for authenticated users only"
  on notes for delete
  using ( auth.role() = 'authenticated' );

create policy "Enable update for authenticated users only"
  on notes for update
  using ( auth.role() = 'authenticated' );

-- 4. Create Storage Bucket for PDFs
insert into storage.buckets (id, name, public)
values ('notes', 'notes', true)
on conflict (id) do nothing;

-- 5. Storage Policies
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'notes' );

create policy "Auth Upload Access"
  on storage.objects for insert
  with check ( bucket_id = 'notes' and auth.role() = 'authenticated' );

create policy "Auth Delete Access"
  on storage.objects for delete
  using ( bucket_id = 'notes' and auth.role() = 'authenticated' );

-- 6. Refresh Schema
notify pgrst, 'reload schema';

-- ==========================================
-- NOTICE BOARD SETUP
-- ==========================================

-- 7. Create Notices Table
create table if not exists notices (
  id bigint primary key generated by default as identity,
  content text not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Enable RLS for Notices
alter table notices enable row level security;

-- 9. Notices Policies
create policy "Public notices are viewable by everyone"
  on notices for select
  using ( true );

create policy "Admins can insert notices"
  on notices for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update notices"
  on notices for update
  using ( auth.role() = 'authenticated' );

-- 10. Default Content
insert into notices (id, content, is_active)
values (1, 'Welcome to NoteShare! Exam updates will appear here.', true)
on conflict (id) do nothing;