-- Run this in your Supabase SQL Editor

-- 1. Create the 'notes' table
create table public.notes (
  id bigint generated by default as identity primary key,
  title text not null,
  subject text not null,
  semester int not null,
  file_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.notes enable row level security;

-- 3. Create Policies for the 'notes' table
-- Allow public read access
create policy "Public notes are viewable by everyone"
  on public.notes for select
  to public
  using (true);

-- Allow authenticated (admin) insert/update/delete access
create policy "Admins can insert notes"
  on public.notes for insert
  to authenticated
  with check (true);

create policy "Admins can update notes"
  on public.notes for update
  to authenticated
  using (true);

create policy "Admins can delete notes"
  on public.notes for delete
  to authenticated
  using (true);

-- 4. Set up Storage
-- Create additional bucket entry if needed, though usually easier to do via Dashboard.
-- Best Practice: Go to Storage -> Create new bucket named 'notes' -> Make it Public.

-- If you want to do it via SQL (requires permissions):
insert into storage.buckets (id, name, public) values ('notes', 'notes', true);

-- Storage Policies
create policy "Give public access to files"
  on storage.objects for select
  to public
  using ( bucket_id = 'notes' );

create policy "Give admin access to upload"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'notes' );
